version: '2'
services:
  elasticsearch:
    build: ./elasticsearch
    depends_on:
      - logstash
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
      - "./elasticsearch/plugins:/usr/share/elasticsearch/plugins"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      elastc:
        ipv4_address: 172.23.0.2

  kibana:
    build: ./kibana
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      elastc:
        ipv4_address: 172.23.0.3

  logstash:
    build: ./logstash
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - "./logstash/pipeline/:/usr/share/logstash/pipeline/"
      - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"
    networks:
      elastc:
        ipv4_address: 172.23.0.4

  filebeat:
    build: ./filebeat
    networks:
      elastc:
        ipv4_address: 172.23.0.5

  apm-server:
    build: ./apm-server
    ports:
      - 8200:8200
    volumes:
      - "./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml"
    networks:
      elastc:
        ipv4_address: 172.23.0.6

networks:
  elastc:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.23.0.0/24
